<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
    <PropertyGroup>
        <Version>1.0.1.4</Version>
        <Description>BOCCHI 新月島與尋寶助手（繁體中文）</Description>
        <PackageProjectUrl>https://github.com/OhKannaDuh/OccultCrescentHelper</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <NoWarn>$(NoWarn);4014</NoWarn>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)/</PathMap>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>DEBUG;TRACE;DEBUG_BUILD</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release_CN'">
        <DefineConstants>RELEASE;TRACE;DALAMUD_CN</DefineConstants>
    </PropertyGroup>
    <!-- Files -->
    <ItemGroup>
        <Content Include="..\assets\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <None Include="..\Translations\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Translations\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
        <None Include="..\Data\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
        </None>
    </ItemGroup>
    <!-- Build the localized Ocelot UI in every configuration. -->
    <ItemGroup>
        <ProjectReference Include="../Ocelot/Ocelot/Ocelot.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="TextCopy" Version="6.2.1"/>
    </ItemGroup>
</Project>
